name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building @otp-auth
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install Packages"
        run: pnpm install --frozen-lockfile

      - name: "Build"
        run: pnpm build

      # - name: Github Release From Changeset
      #   uses: changesets/action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
