name: Publish to JSR @otp-auth/core
on:
  push:
    tags:
      - "@otp-auth/core@*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install PNPM Packages"
        run: pnpm install --frozen-lockfile

      - name: "Publishing to JSR registry @otp-auth/core"
        run: pnpm --filter @otp-auth/core publish:jsr
