name: Publish to NPM @otp-auth/client

on:
  push:
    branches:
      - main

    tags: -'@otp-auth/client@*'

jobs:
  publish-otp-auth-client:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install PNPM Packages"
        run: pnpm install --frozen-lockfile

      - name: "Publishing to npm registry"
        run: pnpm publish --filter @packages/client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
