name: Publish to NPM @otp-auth/client

on:
  push:
    branches:
      - main

    tags: -'@otp-auth/client@*'

permissions:
  id-token: write
  attestations: write

jobs:
  publish-otp-auth-client:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org:_authToken=$NPM_TOKEN
          scope: "@otp-auth"
          cache: "pnpm"

      - name: "Install PNPM Packages"
        run: pnpm install --frozen-lockfile

      - name: "Publishing to NPM registry @otp-auth/client"
        run: pnpm --filter @otp-auth/client publish:npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "${{ github.workspace }}/otp-auth"
